### ISSUE TITLE
How to reload the "gen" process?

### ISSUE THREAD

**Issue by jatins** [redwoodjs/graphql#3060]
👋 Hi! Started playing around with redwood yesterday. 

**Setup**
I am running redwood dev server inside vagrant and editing code via VS code remote ssh setup. I am accessing the website in browser via vagrant port forwarding. 

**Issue**
The "gen" process invariably stops picking up changes after 5-6 edits. So, in first few edits I see these logs
```
gen | Modified Page:  web/src/pages/HomePage/HomePage.tsx 
gen | Modified Page:  web/src/pages/AboutPage/AboutPage.tsx
```

but after few more **it stops picking up changes** for some reasons, I don't see any logs and browser doesn't refresh either.

**Ask**
Is there a way to re-trigger or reload the `gen` process without affecting `api` and `web` processes? I don't want to do entire "yarn rw dev" again from scratch since it takes time.

**Comment by thedavidprice** [comment]
Hi there, @jatins Welcome to Redwood.

I think the command `yarn rw g types` is what you're looking for (as it's used under the hood along with the dev server).

```
$ yarn rw generate --help
yarn run v1.22.10
$/node_modules/.bin/rw generate --help
rw generate <type>

Generate boilerplate code and type definitions

Commands:
  rw generate types                 Generate supplementary code
  rw generate cell <name>           Generate a cell component
  rw generate component <name>      Generate a component
  rw generate dataMigration <name>  Generate a data migration
  rw generate function <name>       Generate a Function
  rw generate layout <name>         Generate a layout component
  rw generate page <name> [path]    Generate a page component
  rw generate scaffold <model>      Generate Pages, SDL, and Services files
                                    based on a given DB schema Model. Also
                                    accepts <path/model>
  rw generate script <name>         Generate a command line script
  rw generate sdl <model>           Generate a GraphQL schema and service
                                    component based on a given DB schema Model
  rw generate secret                Generates a secret key using a
                                    cryptographically-secure source of entropy
  rw generate service <name>        Generate a service component
  rw generate util <util>           WARNING: deprecated. Use "yarn rw setup"
                                    command.                        [aliases: u]

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --cwd      Working directory to use (where `redwood.toml` is located.)

Also see the Redwood CLI Reference
(​https://redwoodjs.com/reference/command-line-interface#generate-alias-g​)

✨  Done in 1.50s.
```

> **Issue**
> The "gen" process invariably stops picking up changes after 5-6 edits. So, in first few edits I see these logs
> ...
> but after few more it stops picking up changes for some reasons, I don't see any logs and browser doesn't refresh either.

^^ This is a problem. I'm looping in @dac09 and @peterp to keep a lookout for this. Once #2938 is merged, the Redwood Dev Server will have undergone an overhaul, so things like this should be resolved.

**Comment by jatins** [comment]
hmm, `yarn rw g types` regenerates the types but looks like those changes aren't picked by "web" server and the page still shows old content. So, I still have to reload `yarn rw dev` pretty much after every 10 or so edits in current setup. Not sure if this is a problem with vagrant setup or if the setup is flaky on Ubuntu in general.

Anyway, thanks for the reply!

**Comment by thedavidprice** [comment]
Looping in @dac09 

Thanks for reporting back @jatins That definitely isn't the behavior we intended. This is _likely_ resolved via #2938 and will be included in the upcoming v0.36 release. There are some significant changes in v0.36 (upgraded Webpack 5 and Jest 27). But if you haven't made custom config implementation, you should be able to try the latest published canary version and see if your issue is resolved. (No need to stay on canary as you might want to roll back.) No pressure but would be great info on our end to know if you still experience the auto-gen "timeout".

`yarn rw upgrade --tag canary` will get you on the latest canary.

**Comment by jatins** [comment]
Just tried right now on canary. Still experiencing the auto-gen "timeout" 🤷 it ...stops after ~5-10 edits.
Also, this is happening on Ubuntu from what I can tell (and not on Mac)
```
vagrant@vagrant:/vagrant/redwoodblog$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by jatins** [comment]
Hi @thedavidprice Thanks for following up! 
Yeah, looks like switching to polling works for nuxt.js https://github.com/nuxt/nuxt.js/issues/7553#issuecomment-646589883

Do you have any pointers on how the toml config is passed forward to webpack? I'll give it a look. 
_Assuming_ there is some chokidar webpack plugin we are using.

**Comment by peterp** [comment]
Hey @jatins 👋

I think the easiest way to do this would be to configure it via an env-var: `RWJS_WATCH_OPTIONS_USE_POLLING='1'`,

There are 3 "watch processes" in RedwoodJS:

* api-server:
https://github.com/redwoodjs/redwood/blob/4e7d2940f95c9216d328a19c9ca555b95a88b3dc/packages/api-server/src/watch.ts#L54-L78
* type-generator:
https://github.com/redwoodjs/redwood/blob/1d0f2fe38fbe109a90fe997e228c6091ec0cdedd/packages/internal/src/generate/watch.ts#L31-L37
*webpack-dev-server

I would set that env-var, then set the `usePolling` option in chokidar if it's enabled:

`usePolling: process.env.RWJS_WATCH_OPTIONS_USE_POLLING === '1'`

For webpack you'll have to read the docs for the and set the configuration option in `webpack.development.js`:
https://github.com/redwoodjs/redwood/blob/01f2eec00a773f5c137a7f39b3f0986e57b15d11/packages/core/config/webpack.development.js#L35-L37

Once that's working - we can consider adding it to the redwood.toml file.

**Comment by jeliasson** [comment]
> 



> [...] The "gen" process invariably stops picking up changes after 5-6 edits. So, in first few edits I see these logs

My two cents; sounds like you need to increase `max_user_watches`. 
- https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
- https://stackoverflow.com/questions/50901127/vsc-unable-to-watch-for-file-changes-in-this-large-workspace-weird

Also, welcome! 👋🏻
