### ISSUE TITLE
[Bug]: When using dbAuth, a @requireAuth check on a mutation will fail if invoked immediately after login

### ISSUE THREAD

**Issue by cannikin** [redwoodjs/graphql#6411]
### What's not working?

From https://community.redwoodjs.com/t/problems-with-backend-auth-when-running-a-mutation-immediately-after-login/4000

> I am having issues running a mutation the @requiresAuth immediately after a user logs in.
>
> Once i get a successful response from the login I attempt to call my mutation and will get an error - ‘UNAUTHENTICATED’ error ‘You don’t have permission to do that.’ occurred in claimVideoMutation
>
> I thought for some reason time may be the solution. So I did a setTimeout to run the mutation every second until it worked. It turns out after about 5 seconds the mutation worked.
>
> I then recalled this ticket - When using dbAuth, don't call `getToken` multiple times per page by cannikin · Pull Request #5816 · redwoodjs/redwood · GitHub (which was an excellent change) but I wonder if this is causing my issue.
>
> So, I attempted to getToken() and also tried reauthenticate() to see if i could get the backend up to date but that did not do the trick.

I'm guessing it's related to the PR he mentioned: https://github.com/redwoodjs/redwood/pull/5816 It sounds like we're memoizing the logout state, so although he successfully logged in, the api side won't acknowledge it until the 5 second expire passes. We specifically have a function that resets the memoize time: https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/dbAuth.ts#L36-L39 and we're even using it within the login function: https://github.com/redwoodjs/redwood/blob/main/packages/auth/src/authClients/dbAuth.ts#L90 so I'm not sure where there bug is occurring...

### How do we reproduce the bug?

Still need to create a reproduction, but it sounds like just having a mutation protected by `@requireAuth` being invoked immediately after a successful login (like recording a `loginCount` on the `User` perhaps) will cause it to happen.

### Are you interested in working on this?

- [X] I'm interested in working on this

**Comment by jtoar** [comment]
@cannikin saw you're interested in this one and assigned yourself, chance it was already fixed and just not linked to the PR? No worries if not! You want to work on it this cycle or should I backlog it?

**Comment by cannikin** [comment]
Hmm, I don't think it's fixed, unless something about decoupling auth happened to fix it? We can actually un-assign me and see if anyone else is interested, and then I can pick it back up if no one comes along. I'm not sure if I'll get to it this cycle!
